### ISSUE TITLE
Feature request: auto-configure credentials with IAM roles

### ISSUE THREAD

**Issue by keithchilders** [mhart/kinesis#10]
Is there any chance you would be willing to do one of the following:

1. Pass this module an already configured aws-sdk instance to use as its request client (aws-sdk already supports IAM roles)

2. Extend your aws4 library to pull credentials from either environment variables or from IAM role (metadata API on-box) in a chaining fashion the same way the aws-sdk does?

**Comment by mhart** [comment]
Yeah, definitely – I actually already have some code that does this (2), I just want to commit it as a separate module (so that it can be reused by others, etc).

You could monkey patch the current `request` method to use the aws-sdk client... probably – I don't imagine it would be *too* hard. But ultimately, yeah, I'll add the IAM lookup (and refreshing when the session expires, etc).

Should be able to get time to do this in the next week or two.

**Comment by cb372** [comment]
+1 this would be really useful

**Comment by keithchilders** [comment]
Any update on this? I didn't want to do a PR since you said you already had code written.

**Comment by mhart** [comment]
Hey, sorry for the delay, finally got around to publishing a separate module for this: https://github.com/mhart/awscred

So, I'll work on updating kinesis now to use this credentials lookup method and we should be good to go.

**Comment by mhart** [comment]
Thanks for the nudge @keithchilders – finally got this in, and released as v1.2.0
